default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: fleamarket_sample_79c_development #アプリケーション名はご自身のものに変更してください

test:
  <<: *default
  database: fleamarket_sample_79c_test #アプリケーション名はご自身のものに変更してください

production:
  <<: *default
  database: fleamarket_sample_79c_production #アプリケーション名はご自身のものに変更してください
  username: root #rootに変更
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /tmp/mysql.sock
